import { Pack } from './types.ts';

export const INITIAL_DATA: Pack[] = [
    {"id":"1","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"External","pack":"Pack1","dataSeeds":"oui","server":"194.163.144.27","disk":"externe","rdps":"repo","password":"LABO@0000","interval":"1-3999","browser":"Chrome","status":"Repoting","countProfiles":"3999","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"2","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"External","pack":"Pack2","dataSeeds":"oui","server":"185.216.75.117","disk":"externe","rdps":"repo","password":"LABO@0000","interval":"1-5000","browser":"Chrome","status":"Repo IPs","countProfiles":"5000","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"3","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"External","pack":"Pack3","dataSeeds":"non","server":"66.94.120.85","disk":"externe","rdps":"repo","password":"LABO@0000","interval":"1-3078","browser":"Chrome","status":"Repo IPs","countProfiles":"3078","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"4","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"External","pack":"Pack4","dataSeeds":"oui","server":"194.163.130.102","disk":"externe","rdps":"repo","password":"LABO@0000","interval":"1-3000","browser":"Chrome","status":"Repoting","countProfiles":"3000","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"5","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack5","dataSeeds":"non","server":"4","disk":"E","rdps":"ECM4_Gmail_1","password":"Password@1.","interval":"1-5000","browser":"Chrome","status":"Repoting","countProfiles":"3746","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"6","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack6","dataSeeds":"non","server":"4","disk":"E","rdps":"ECM4_Gmail_2","password":"Password@2.","interval":"5001-10000","browser":"Chrome","status":"Verification","countProfiles":"3791","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"7","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack7","dataSeeds":"non","server":"4","disk":"E","rdps":"ECM4_Gmail_3","password":"Password@3.","interval":"10001-15000","browser":"Chrome","status":"Repo IPs","countProfiles":"3428","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"8","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack8","dataSeeds":"non","server":"3","disk":"G","rdps":"ECM4_Gmail_1","password":"Password@1.","interval":"15001-20000","browser":"Chrome","status":"Repoting","countProfiles":"2560","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"9","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack9","dataSeeds":"non","server":"3","disk":"G","rdps":"ECM4_Gmail_2","password":"Password@2.","interval":"20001-25000","browser":"Chrome","status":"Repo IPs","countProfiles":"3025","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"10","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack10","dataSeeds":"non","server":"4","disk":"F","rdps":"ECM4_Gmail_4","password":"Password@4.","interval":"28793-30391","browser":"Chromium","status":"ADD contact","countProfiles":"774","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"11","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack11","dataSeeds":"non","server":"7","disk":"H","rdps":"ECM4_Gmail_1","password":"tHp**DHpQK7g","interval":"31152-37181","browser":"webview","status":"Repoting","countProfiles":"4251","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"12","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack12","dataSeeds":"non","server":"7","disk":"F","rdps":"ECM4_Gmail_2","password":"(DC%c(D#V5f*","interval":"37182-39179","browser":"webview","status":"Verification","countProfiles":"552","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"13","entity":"ECM4","entityProd":"ECM4","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack13","dataSeeds":"non","server":"3","disk":"I","rdps":"ECM4_gmail_5","password":"Password@5.","interval":"40000-42000","browser":"webview","status":"Repoting","countProfiles":"1989","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"14","entity":"ECM4","entityProd":"ECM4","platform":"iMACROS","team":"A","localExternal":"External","pack":"Pack14","dataSeeds":"non","server":"144.126.130.165","disk":"externe","rdps":"repo4","password":"ECM4@6666","interval":"85--1782","browser":"palemoon","status":"Repo IPs","countProfiles":"1711","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"15","entity":"ECM4","entityProd":"ECM4","platform":"iMACROS","team":"A","localExternal":"External","pack":"Pack15","dataSeeds":"non","server":"194.163.144.27","disk":"externe","rdps":"repo1","password":"ECM4@6666","interval":"3--13753","browser":"palemoon","status":"Repo IPs","countProfiles":"1914","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"23","entity":"ECM7","entityProd":"ECM5","platform":"ECM_APP","team":"A","localExternal":"Local","pack":"Pack23","dataSeeds":"oui","server":"4","disk":"D","rdps":"ECM5_gmail_1","password":"Njs-.;:pg,rb6Xyw5LW49/","interval":"1-5000","browser":"Chrome","status":"Repoting","countProfiles":"3895","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"45","entity":"ECM7","entityProd":"ECM3","platform":"ECM_APP","team":"B","localExternal":"Local","pack":"Pack45","dataSeeds":"non","server":"1","disk":"D","rdps":"ecm3_gmail_1","password":"Password@1.","interval":"1-5000","browser":"Chrome","status":"Repoting","countProfiles":"2969","backup":"Non","totalSeedsOk":"","notes":""},
    {"id":"80","entity":"ECM10","entityProd":"ECM2","platform":"ECM_APP","team":"B","localExternal":"External","pack":"Pack80","dataSeeds":"non","server":"70.36.107.56","disk":"externe","rdps":"admin","password":"ECM2_uC84","interval":"1---6000","browser":"Chrome","status":"ADD contact","countProfiles":"5751","backup":"Non","totalSeedsOk":"","notes":""}
];

export const STATUS_OPTIONS = ["Repo IPs", "Verification", "ADD contact", "Repoting", "EMPTY", "LOGING", "Hold", "DOWN"];
export const ENTITY_OPTIONS = ["ECM4", "ECM7", "ECM10"];
export const PLATFORM_OPTIONS = ["ECM_APP", "iMACROS"];
export const TEAM_OPTIONS = ["A", "B", "C", "Empty"];
export const LOCATION_OPTIONS = ["Local", "External"];
